config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'store#home', as: 'store_home'

  get 'store/index'

  get 'all_users_path' => 'users#index'

  get 'admin' => 'admin#index'
  get '/products/show/' => 'products#one'
  get '/store/filter' => 'store#filter_products'
  get '/orders/o' => 'orders#one'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
    get 'logout' => :destroy
  end

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  resources :products

  resources :line_items do
    put 'decrease', on: :member
    put 'increase', on: :member
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord

  has_many :line_items # rubocop:disable Rails/HasManyOrHasOneDependent
  has_many :orders, through: :line_items

  enum prod_types: {
    'Books' => 0,
    'Sunglasses' => 1,
    'Other' => 2
  }

  before_destroy :ensure_not_referenced_by_any_line_item
  before_update :change_type
  validates :title, :description, presence: true
  validates :price, numericality: { greater_than_or_equal_to: 0.01 }
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: {
    with: /\.(gif|jpg|png)\Z/i,
    message: 'must be a URL for GIF, JPG or PNG image.'
  }

  private

  # ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_line_item
    unless line_items.empty?
      errors.add(:base, 'Line Items present')
      throw :abort
    end
  end

  def change_type
    self.prod_type = 'Books'
  end

end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController

  before_action :set_product, only: %i[show edit update destroy]
  skip_before_action :authorize, only: :one
  layout 'admin_application', except: :one

  include CurrentCart
  before_action :set_cart

  def index
    @products = Product.all
  end

  def show
  end

  def one
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_url
    else
      render :new
    end
  end

  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    message = if @product.destroy
                'Product was successfully destroyed.'
              else
                'Product could not be deleted, because is added to cart.'
              end

    redirect_to products_url, notice: message
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:title, :description, :image_url, :price, :prod_type)
  end

end

app/views/products/_form.html.slim
= form_for(product) do |f|
  - if product.errors.any?
    #error_explanation
      h2
        = pluralize(product.errors.count, "error")
        |  prohibited this product from being saved:
      ul
        - product.errors.full_messages.each do |message|
          li
            = message
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description, rows: 4, cols: 50
  .field
    = f.label :prod_type
    = f.select :prod_type, Product.prod_types.keys, prompt: 'Select product type'
  .field
    = f.label :price
    = f.text_field :price, size: 13
    |  (€) 
  .actions
    = f.submit

app/views/products/edit.html.slim
h2.product_header Editing Product
.products_column
  = render 'form', product: @product
  .back_button
    = link_to 'Back', products_path

app/views/products/index.html.slim
p#notice
  = notice
h2#Products.product_header Products
.products_column
  p#new_product_div
    = link_to 'New product', new_product_path
  table
    thead
      tr
        th
        th
        th
        th
        th[colspan="3"]
    - @products.each do |product|
      tr
        td
          - if (product.image_url != nil)
            = image_tag(product.image_url, class: 'list_image')
        td.list_description
          = link_to product.title, product, action: "show"
          .categ_div
            | Category: 
            span.prod_categ
              = product.prod_type
        td.list_actions
          = link_to 'Edit', edit_product_path(product)
        td.list_actions
          = link_to 'Delete', product, method: :delete
br

app/views/products/new.html.slim
h2.product_header New Product
.products_column
  = render 'form', product: @product
  .back_button
    = link_to 'Back', products_path

app/views/products/one.html.slim
p#notice
  = notice
.one_product_page
  p
    - if (@product.image_url != nil)
      = image_tag(@product.image_url, class: 'list_image')
  p

  h2
    = @product.title
  p
    strong Description: 
    = strip_tags(@product.description)
  p
    strong Type: 
    = @product.prod_type
  p
    strong Price: 
    = number_to_currency(@product.price)
  = button_to 'Add to Cart', line_items_path(product_id: @product), remote: true

app/views/products/show.html.slim
p#notice
  = notice
.products_column
  p
    - if (@product.image_url != nil)
      = image_tag(@product.image_url, class: 'list_image')
  p
    strong Title: 
    = @product.title
  p
    strong Description: 
    = strip_tags(@product.description)
  p
    strong Type: 
    = @product.prod_type
  p
    strong Price: 
    = number_to_currency(@product.price)
  .back_button
    = link_to 'Edit', edit_product_path(@product)
    |  | 
    = link_to 'Back', products_path