config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'store#home', as: 'store_home'

  get 'store/index'

  get 'all_users_path' => 'users#index'

  get 'admin' => 'admin#index'
  get '/products/show/' => 'products#one'
  get '/store/filter' => 'store#filter_products'
  get '/orders/o' => 'orders#one'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
    get 'logout' => :destroy
  end

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  resources :products

  resources :line_items do
    put 'decrease', on: :member
    put 'increase', on: :member
  end
end

app/models/line_item.rb
# frozen_string_literal: true

class LineItem < ApplicationRecord

  belongs_to :order, optional: true
  belongs_to :product, optional: true
  belongs_to :cart

  delegate :title, to: :product, prefix: true

  def total_price
    product.price * quantity
  end

end

app/controllers/line_items_controller.rb
# frozen_string_literal: true

class LineItemsController < ApplicationController

  skip_before_action :authorize, only: %i[create decrease increase destroy]

  include CurrentCart
  before_action :set_cart, only: %i[create]
  before_action :set_line_item, only: %i[show edit update destroy]

  def index
    @line_items = LineItem.all
  end

  def show
  end

  def new
    @line_item = LineItem.new
  end

  def edit
  end

  def decrease
    @cart = Cart.find(session[:cart_id])
    @line_item = @cart.decrease(params[:id])

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to store_path, notice: 'Line item was successfully updated.' }
        format.js   { @current_item = @line_item }
        format.json { head :ok }
      else
        format.html { render action: 'edit' }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def increase
    @cart = Cart.find(session[:cart_id])
    @line_item = @cart.increase(params[:id])

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to store_path, notice: 'Line item was successfully updated.' }
        format.js   { @current_item = @line_item }
        format.json { head :ok }
      else
        format.html { render action: 'edit' }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def create
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to store_index_url }
        format.js   { @current_item = @line_item }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to store_home_url, notice: 'Item successfully deleted from cart.' }
      format.json { head :no_content }
    end
  end

  private

  def set_line_item
    @line_item = LineItem.find(params[:id])
  end

  def line_item_params
    params.require(:line_item).permit(:product_id)
  end

end

app/views/line_items/_form.html.erb
<%= form_for(line_item) do |f| %>
  <% if line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %>
    <%= f.text_field :product_id %>
  </div>

  <div class="field">
    <%= f.label :cart_id %>
    <%= f.text_field :cart_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<% if line_item == @current_item %>
  <tr id="current_item" class="cart_row">
<% else %>
  <tr class="cart_row">
<% end %>
  <td><%= line_item.quantity %>&times;</td>
  <td><%= line_item.product.title %></td>
  <td class="item_price"><%= number_to_currency(line_item.total_price) %></td>

  <td class="quantity"><%= link_to "↓", decrease_line_item_path(line_item), :method => :put, remote: true %></td>
  <td class="quantity"><%= link_to "↑", increase_line_item_path(line_item), :method => :put, remote: true %></td>

  <td id="delete_button"><%= link_to 'X', line_item, method: :delete%></td>
</tr>

app/views/line_items/create.js.erb
$('#notice').hide();

if ($('#cart tr').length == 1) { $('#cart').show('blind', 1000); }

$('#cart').html("<%=j render(@cart) %>");

$('#current_item').css({'background-color':'white'}).
  animate({'background-color':'#A6ADB5'}, 1000);

app/views/line_items/decrease.js.erb
$('#cart').html("<%= escape_javascript(render(@cart)) %>");
$('#current_item').css({'background-color':'white'}).animate({'background-color':'#A6ADB5'}, 1000);
if ($('#cart tr').length==1) {
    $('#cart').hide('blind', 1000);
}

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/increase.js.erb
$('#cart').html("<%=j render @cart %>");
$('#current_item').css({'background-color':'white'}).animate({'background-color':'#A6ADB5'}, 1000);

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Line Items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Cart</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.product %></td>
        <td><%= line_item.cart %></td>
        <td><%= link_to 'Show', line_item %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' }  %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line Item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form', line_item: @line_item %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @line_item.product %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>