config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'store#home', as: 'store_home'

  get 'store/index'

  get 'all_users_path' => 'users#index'

  get 'admin' => 'admin#index'
  get '/products/show/' => 'products#one'
  get '/store/filter' => 'store#filter_products'
  get '/orders/o' => 'orders#one'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
    get 'logout' => :destroy
  end

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  resources :products

  resources :line_items do
    put 'decrease', on: :member
    put 'increase', on: :member
  end
end

app/views/layouts/admin_application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>ST Online Store</title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => 'reload' %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => 'reload' %>
    <%= csrf_meta_tags %>

</head>

<body class="<%= controller.controller_name %>">

  <div id="banner">
    ST ONLINE STORE
  </div>

  <div class="columns">
    <div id="menu">
      <ul>
        <li><%= link_to 'Admin', admin_path %></li>
        <% if session[:user_id] %>
            <li class="admin_menu"><%= link_to 'Orders', orders_path %></li>
            <li class="admin_menu"><%= link_to 'Products', products_path %></li>
            <!-- <li class="admin_menu"><%= link_to 'Users', users_path %></li> -->
            <li><%= link_to 'Logout', logout_path, method: :delete %></li>
        <% else %>
            <li><%= link_to 'Login', login_path %></li>
            <li><%= link_to 'Register', new_user_path %></li>
        <% end %>

      </ul>

    </div>
  </div>

  <div class="columns" id="white_bar">
  </div>

  <div class="columns" id="column2">

    <div id="side">
      <div id="cart">
        <% if @cart and not session[:user_id]%>
          <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
            <%= render @cart %>
          <% end %>
        <% end %>
      </div>
    </div>

    <div id="main">
      <%= yield %>
    </div>
  </div>

</body>

<div class="footer">
  <p><strong>Powered by UT</strong></p>
</div>


</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>ST Online Store</title>
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => 'reload' %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => 'reload' %>
    <%= csrf_meta_tags %>

</head>

<body class="<%= controller.controller_name %>">

  <div id="banner">
    ST ONLINE STORE
  </div>

  <div class="columns">
    <div id="menu">
      <ul>

        <li><a href="/">Home</a></li>
        <li><%= link_to "Sunglasses", controller: "store", action: "filter_products", sort: "Sunglasses" %></li>
        <li><%= link_to "Books", controller: "store", action: "filter_products", sort: "Books" %></li>
        <li><%= link_to "Other", controller: "store", action: "filter_products", sort: "Other" %></li>
      </ul>

    </div>
  </div>

  <div class="columns" id="white_bar">
  </div>

  <div class="columns" id="column2">

    <div id="side">
      <div id="cart">
        <% if @cart %>
          <%= render @cart %>
        <% end %>
      </div>
    </div>

    <div id="main">
      <%= yield %>
    </div>
  </div>

</body>

<div class="footer">
  <p><strong>Powered by UT</strong></p>
</div>


</html>